// Generated by CoffeeScript 1.7.1
(function() {
  var FireWorks, PI, clearPoint,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  PI = Math.PI;

  (function(w, r) {
    return w['r' + r] = w['r' + r] || w['webkitR' + r] || w['mozR' + r] || w['msR' + r] || w['oR' + r] || function(c) {
      return w.setTimeout(c, 1000 / 60);
    };
  })(window, 'equestAnimationFrame');

  clearPoint = function(ctx, x, y, size) {
    return requestAnimationFrame(function() {
      ctx.save();
      ctx.beginPath();
      ctx.arc(x, y, size * 1.2, 0, PI * 2, true);
      ctx.clip();
      ctx.clearRect(0, 0, this.width, this.height);
      return ctx.restore();
    });
  };

  FireWorks = (function() {
    function FireWorks(_arg) {
      var angle, i, speed, _i, _ref, _ref1;
      _ref = _arg != null ? _arg : {}, this.quantity = _ref.quantity, this.size = _ref.size, this.circle = _ref.circle, this.gravity = _ref.gravity, this.speed = _ref.speed, this.color = _ref.color, this.width = _ref.width, this.height = _ref.height;
      this.render = __bind(this.render, this);
      if (this.quantity == null) {
        this.quantity = 256;
      }
      if (this.size == null) {
        this.size = 4.8;
      }
      if (this.circle == null) {
        this.circle = 0.965;
      }
      if (this.gravity == null) {
        this.gravity = 1.2;
      }
      if (this.speed == null) {
        this.speed = 7.8;
      }
      if (this.color == null) {
        this.color = '#ffcc00';
      }
      if (this.width == null) {
        this.width = 640;
      }
      if (this.height == null) {
        this.height = 480;
      }
      this.canvas = document.createElement('canvas');
      this.ctx = this.canvas.getContext('2d');
      this.canvas.width = 640;
      this.canvas.height = 480;
      this.particles = [];
      this.frame = 0;
      for (i = _i = 0, _ref1 = this.quantity; 0 <= _ref1 ? _i < _ref1 : _i > _ref1; i = 0 <= _ref1 ? ++_i : --_i) {
        angle = Math.random() * PI * 2;
        speed = Math.random() * this.speed;
        this.particles.push({
          centerX: this.width / 2,
          centerY: this.height / 2,
          velocityX: Math.cos(angle) * speed,
          velocityY: Math.sin(angle) * speed
        });
      }
    }

    FireWorks.prototype.dispose = function() {
      delete this.quantity;
      delete this.size;
      delete this.circle;
      delete this.gravity;
      delete this.speed;
      delete this.color;
      delete this.width;
      delete this.height;
      delete this.ctx;
      this.parent.removeChild(this.canvas);
      delete this.canvas;
      this.particles.length = 0;
      delete this.particles;
      return Object.freeze(this);
    };

    FireWorks.prototype.appendTo = function(query) {
      this.parent = document.querySelector(query);
      return this.parent.appendChild(this.canvas);
    };

    FireWorks.prototype.updateParticles = function() {
      return this.particles.forEach((function(_this) {
        return function(p, index) {
          var _ref, _ref1;
          p.centerX += p.velocityX;
          p.centerY += p.velocityY;
          p.velocityX *= _this.circle;
          p.velocityY *= _this.circle;
          p.centerY += _this.gravity;
          if (_this.size > 0.1 && (0 < (_ref = p.centerX) && _ref < _this.width) && (0 < (_ref1 = p.centerY) && _ref1 < _this.height)) {
            return '';
          } else {
            return _this.particles.splice(_this.particles.indexOf(p), 1);
          }
        };
      })(this));
    };

    FireWorks.prototype.drawParticles = function() {
      this.ctx.fillStyle = this.frame % 2 ? "rgba(256, 256, 256, 0.8)" : this.color;
      return this.particles.forEach((function(_this) {
        return function(p, index) {
          _this.ctx.beginPath();
          _this.ctx.arc(p.centerX, p.centerY, _this.size, 0, PI * 2, true);
          return _this.ctx.fill();
        };
      })(this));
    };

    FireWorks.prototype.render = function() {
      if (!this.particles.length) {
        this.dispose();
        if (typeof this.onFinish === "function") {
          this.onFinish();
        }
      }
      this.ctx.clearRect(0, 0, this.width, this.height);
      this.frame++;
      this.updateParticles();
      this.drawParticles();
      this.size *= this.circle;
      this.ctx.fillStyle = 'rgba(0, 0, 0, 0.4)';
      return requestAnimationFrame(this.render);
    };

    return FireWorks;

  })();

  window.addEventListener('load', function() {
    var fw;
    fw = new FireWorks;
    fw.appendTo('body');
    return fw.render();
  });

}).call(this);
